export const copy = {
  brand: 'shelf',
  tagline: 'Your vinyl collection',
  nav: {
    home: 'Home',
    explore: 'Explore',
    shelf: 'My Shelf',
  },
  home: {
    heroTitle: 'Your records, one shelf',
    heroText: 'Search albums and artists, then save the vinyl you own.',
    ctaExplore: 'Explore',
    ctaShelf: 'My Shelf',
    charts: 'Featured albums',
    artists: 'Featured artists',
    recent: 'Recently opened',
  },
  explore: {
    title: 'Explore',
    subtitle: 'Search by artist or album name.',
    albums: 'Albums',
    artists: 'Artists',
    placeholder: 'Search albums or artists…',
    recent: 'Recent searches',
    clearRecent: 'Clear',
    noResults: 'Nothing found. Try another name.',
    emptyHint: 'Type a name to search.',
  },
  shelf: {
    title: 'My Shelf',
    subtitle: 'Albums you saved in this browser.',
    empty: 'Your shelf is empty. Find an album and add it.',
    emptyCta: 'Find albums',
    count: 'records',
    clear: 'Clear shelf',
    clearConfirm: 'Remove all albums from your shelf?',
    note: 'Note',
    condition: 'Condition',
    added: 'Added',
    remove: 'Remove',
    editNote: 'Edit note',
    sortNewest: 'Newest first',
    sortAlpha: 'A to Z',
  },
  album: {
    tracks: 'Tracklist',
    label: 'Label',
    released: 'Released',
    add: 'Add to shelf',
    onShelf: 'On your shelf',
    remove: 'Remove from shelf',
    genres: 'Genre',
    style: 'Style',
  },
  artist: {
    albums: 'Albums',
    fans: 'fans',
  },
  modal: {
    close: 'Close',
    addTitle: 'Add to shelf',
    save: 'Save',
    cancel: 'Cancel',
    condition: 'Condition',
    notePlaceholder: 'Optional note',
  },
  conditions: {
    mint: 'Mint',
    near_mint: 'Near mint',
    very_good: 'Very good',
    good: 'Good',
    fair: 'Fair',
  },
  common: {
    loading: 'Loading…',
    error: 'Something went wrong. Try again.',
    retry: 'Retry',
    back: 'Back',
  },
} as const

export type Copy = typeof copy
